# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Get it working, then make it better.'
tagline:          ''
description:      'Made by <a href="https://twitter.com/terrcin" target="_blank">@terrcin</a>.'
url:              http://terrcin.nz
baseurl:          /

author:
  name:           'Nahum'
  url:            https://twitter.com/terrcin

paginate:         5
