# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            terrcin.tv
tagline:          'Get it working, then make it better'
description:      'Enter some sort of proper description here! Made by <a href="https://twitter.com/terrcin" target="_blank">@terrcin</a>.'
url:              http://terrcin.nz
baseurl:          /

author:
  name:           'Nahum'
  url:            https://twitter.com/terrcin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/terrcin/terrcin.github.io
